/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrcanessConfidenceRange {
    #[serde(rename = "min")]
    pub min: f64,
    #[serde(rename = "max")]
    pub max: f64,
}

impl BrcanessConfidenceRange {
    pub fn new(min: f64, max: f64) -> BrcanessConfidenceRange {
        BrcanessConfidenceRange {
            min,
            max,
        }
    }
}

