/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BroadConsentReasonMissing {
    #[serde(rename = "organizational-issues")]
    OrganizationalIssues,
    #[serde(rename = "technical-issues")]
    TechnicalIssues,
    #[serde(rename = "patient-inability")]
    PatientInability,
    #[serde(rename = "other-patient-reason")]
    OtherPatientReason,
    #[serde(rename = "consent-not-returned")]
    ConsentNotReturned,
    #[serde(rename = "patient-refusal")]
    PatientRefusal,

}

impl std::fmt::Display for BroadConsentReasonMissing {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OrganizationalIssues => write!(f, "organizational-issues"),
            Self::TechnicalIssues => write!(f, "technical-issues"),
            Self::PatientInability => write!(f, "patient-inability"),
            Self::OtherPatientReason => write!(f, "other-patient-reason"),
            Self::ConsentNotReturned => write!(f, "consent-not-returned"),
            Self::PatientRefusal => write!(f, "patient-refusal"),
        }
    }
}

impl Default for BroadConsentReasonMissing {
    fn default() -> BroadConsentReasonMissing {
        Self::OrganizationalIssues
    }
}

