/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Chromosome {
    #[serde(rename = "chr5")]
    Chr5,
    #[serde(rename = "chr6")]
    Chr6,
    #[serde(rename = "chr8")]
    Chr8,
    #[serde(rename = "chr1")]
    Chr1,
    #[serde(rename = "chrX")]
    ChrX,
    #[serde(rename = "chr12")]
    Chr12,
    #[serde(rename = "chr11")]
    Chr11,
    #[serde(rename = "chr17")]
    Chr17,
    #[serde(rename = "chr21")]
    Chr21,
    #[serde(rename = "chr19")]
    Chr19,
    #[serde(rename = "chr14")]
    Chr14,
    #[serde(rename = "chr9")]
    Chr9,
    #[serde(rename = "chr4")]
    Chr4,
    #[serde(rename = "chrMT")]
    ChrMt,
    #[serde(rename = "chr2")]
    Chr2,
    #[serde(rename = "chrY")]
    ChrY,
    #[serde(rename = "chr3")]
    Chr3,
    #[serde(rename = "chr7")]
    Chr7,
    #[serde(rename = "chr13")]
    Chr13,
    #[serde(rename = "chr10")]
    Chr10,
    #[serde(rename = "chr15")]
    Chr15,
    #[serde(rename = "chr22")]
    Chr22,
    #[serde(rename = "chr18")]
    Chr18,
    #[serde(rename = "chr16")]
    Chr16,
    #[serde(rename = "chr20")]
    Chr20,

}

impl std::fmt::Display for Chromosome {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Chr5 => write!(f, "chr5"),
            Self::Chr6 => write!(f, "chr6"),
            Self::Chr8 => write!(f, "chr8"),
            Self::Chr1 => write!(f, "chr1"),
            Self::ChrX => write!(f, "chrX"),
            Self::Chr12 => write!(f, "chr12"),
            Self::Chr11 => write!(f, "chr11"),
            Self::Chr17 => write!(f, "chr17"),
            Self::Chr21 => write!(f, "chr21"),
            Self::Chr19 => write!(f, "chr19"),
            Self::Chr14 => write!(f, "chr14"),
            Self::Chr9 => write!(f, "chr9"),
            Self::Chr4 => write!(f, "chr4"),
            Self::ChrMt => write!(f, "chrMT"),
            Self::Chr2 => write!(f, "chr2"),
            Self::ChrY => write!(f, "chrY"),
            Self::Chr3 => write!(f, "chr3"),
            Self::Chr7 => write!(f, "chr7"),
            Self::Chr13 => write!(f, "chr13"),
            Self::Chr10 => write!(f, "chr10"),
            Self::Chr15 => write!(f, "chr15"),
            Self::Chr22 => write!(f, "chr22"),
            Self::Chr18 => write!(f, "chr18"),
            Self::Chr16 => write!(f, "chr16"),
            Self::Chr20 => write!(f, "chr20"),
        }
    }
}

impl Default for Chromosome {
    fn default() -> Chromosome {
        Self::Chr5
    }
}

