/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Claim {
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<models::ClaimStageCoding>,
    #[serde(rename = "requestedMedication", skip_serializing_if = "Option::is_none")]
    pub requested_medication: Option<Vec<models::AtcUnregisteredMedicationCoding>>,
    #[serde(rename = "recommendation")]
    pub recommendation: models::Reference,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "issuedOn")]
    pub issued_on: String,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
}

impl Claim {
    pub fn new(recommendation: models::Reference, id: String, issued_on: String, patient: models::Reference) -> Claim {
        Claim {
            stage: None,
            requested_medication: None,
            recommendation,
            id,
            issued_on,
            patient,
        }
    }
}

