/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Cnv {
    #[serde(rename = "localization", skip_serializing_if = "Option::is_none")]
    pub localization: Option<Vec<models::BaseVariantLocalizationCoding>>,
    #[serde(rename = "reportedFocality", skip_serializing_if = "Option::is_none")]
    pub reported_focality: Option<String>,
    #[serde(rename = "reportedAffectedGenes", skip_serializing_if = "Option::is_none")]
    pub reported_affected_genes: Option<Vec<models::Coding>>,
    #[serde(rename = "totalCopyNumber", skip_serializing_if = "Option::is_none")]
    pub total_copy_number: Option<i32>,
    #[serde(rename = "cnA", skip_serializing_if = "Option::is_none")]
    pub cn_a: Option<f64>,
    #[serde(rename = "externalIds", skip_serializing_if = "Option::is_none")]
    pub external_ids: Option<Vec<models::VariantExternalId>>,
    #[serde(rename = "startRange", skip_serializing_if = "Option::is_none")]
    pub start_range: Option<models::CnvStartRange>,
    #[serde(rename = "type")]
    pub r#type: models::CnvTypeCoding,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
    #[serde(rename = "endRange", skip_serializing_if = "Option::is_none")]
    pub end_range: Option<models::CnvEndRange>,
    #[serde(rename = "chromosome")]
    pub chromosome: models::Chromosome,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "cnB", skip_serializing_if = "Option::is_none")]
    pub cn_b: Option<f64>,
    #[serde(rename = "relativeCopyNumber", skip_serializing_if = "Option::is_none")]
    pub relative_copy_number: Option<f64>,
    #[serde(rename = "copyNumberNeutralLoH", skip_serializing_if = "Option::is_none")]
    pub copy_number_neutral_lo_h: Option<Vec<models::Coding>>,
}

impl Cnv {
    pub fn new(r#type: models::CnvTypeCoding, patient: models::Reference, chromosome: models::Chromosome, id: String) -> Cnv {
        Cnv {
            localization: None,
            reported_focality: None,
            reported_affected_genes: None,
            total_copy_number: None,
            cn_a: None,
            external_ids: None,
            start_range: None,
            r#type,
            patient,
            end_range: None,
            chromosome,
            id,
            cn_b: None,
            relative_copy_number: None,
            copy_number_neutral_lo_h: None,
        }
    }
}

