/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConsentProvisionType {
    #[serde(rename = "deny")]
    Deny,
    #[serde(rename = "permit")]
    Permit,

}

impl std::fmt::Display for ConsentProvisionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Deny => write!(f, "deny"),
            Self::Permit => write!(f, "permit"),
        }
    }
}

impl Default for ConsentProvisionType {
    fn default() -> ConsentProvisionType {
        Self::Deny
    }
}

