/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnaFusionFusionPartner5prime {
    #[serde(rename = "chromosome")]
    pub chromosome: models::Chromosome,
    #[serde(rename = "gene")]
    pub gene: models::Coding,
    #[serde(rename = "position")]
    pub position: f64,
}

impl DnaFusionFusionPartner5prime {
    pub fn new(chromosome: models::Chromosome, gene: models::Coding, position: f64) -> DnaFusionFusionPartner5prime {
        DnaFusionFusionPartner5prime {
            chromosome,
            gene,
            position,
        }
    }
}

