/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnaFusion {
    #[serde(rename = "fusionPartner3prime")]
    pub fusion_partner3prime: models::DnaFusionFusionPartner3prime,
    #[serde(rename = "localization", skip_serializing_if = "Option::is_none")]
    pub localization: Option<Vec<models::BaseVariantLocalizationCoding>>,
    #[serde(rename = "fusionPartner5prime")]
    pub fusion_partner5prime: models::DnaFusionFusionPartner5prime,
    #[serde(rename = "externalIds", skip_serializing_if = "Option::is_none")]
    pub external_ids: Option<Vec<models::VariantExternalId>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "reportedNumReads")]
    pub reported_num_reads: i32,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
}

impl DnaFusion {
    pub fn new(fusion_partner3prime: models::DnaFusionFusionPartner3prime, fusion_partner5prime: models::DnaFusionFusionPartner5prime, id: String, reported_num_reads: i32, patient: models::Reference) -> DnaFusion {
        DnaFusion {
            fusion_partner3prime,
            localization: None,
            fusion_partner5prime,
            external_ids: None,
            id,
            reported_num_reads,
            patient,
        }
    }
}

