/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FamilyMemberHistory {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
    #[serde(rename = "relationship")]
    pub relationship: models::FamilyMemberHistoryRelationshipTypeCoding,
}

impl FamilyMemberHistory {
    pub fn new(id: String, patient: models::Reference, relationship: models::FamilyMemberHistoryRelationshipTypeCoding) -> FamilyMemberHistory {
        FamilyMemberHistory {
            id,
            patient,
            relationship,
        }
    }
}

