/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneAlterationReference {
    #[serde(rename = "variant")]
    pub variant: models::Reference,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "gene", skip_serializing_if = "Option::is_none")]
    pub gene: Option<models::Coding>,
}

impl GeneAlterationReference {
    pub fn new(variant: models::Reference) -> GeneAlterationReference {
        GeneAlterationReference {
            variant,
            display: None,
            gene: None,
        }
    }
}

