/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MolecularDiagnosticReportTypeCoding {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl MolecularDiagnosticReportTypeCoding {
    pub fn new(code: Code) -> MolecularDiagnosticReportTypeCoding {
        MolecularDiagnosticReportTypeCoding {
            code,
            display: None,
            system: None,
            version: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "fusion-panel")]
    FusionPanel,
    #[serde(rename = "genome-short-read")]
    GenomeShortRead,
    #[serde(rename = "array")]
    Array,
    #[serde(rename = "FISH")]
    Fish,
    #[serde(rename = "exome")]
    Exome,
    #[serde(rename = "gene-panel")]
    GenePanel,
    #[serde(rename = "PCR")]
    Pcr,
    #[serde(rename = "karyotyping")]
    Karyotyping,
    #[serde(rename = "panel")]
    Panel,
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "genome-long-read")]
    GenomeLongRead,
    #[serde(rename = "other")]
    Other,
}

impl Default for Code {
    fn default() -> Code {
        Self::FusionPanel
    }
}

