/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MtbTherapyStatusReasonCoding {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl MtbTherapyStatusReasonCoding {
    pub fn new(code: Code) -> MtbTherapyStatusReasonCoding {
        MtbTherapyStatusReasonCoding {
            code,
            display: None,
            system: None,
            version: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "patient-wish")]
    PatientWish,
    #[serde(rename = "progression")]
    Progression,
    #[serde(rename = "payment-refused")]
    PaymentRefused,
    #[serde(rename = "deterioration")]
    Deterioration,
    #[serde(rename = "patient-death")]
    PatientDeath,
    #[serde(rename = "regular-completion")]
    RegularCompletion,
    #[serde(rename = "regular-completion-with-dosage-reduction")]
    RegularCompletionWithDosageReduction,
    #[serde(rename = "best-supportive-care")]
    BestSupportiveCare,
    #[serde(rename = "lost-to-fu")]
    LostToFu,
    #[serde(rename = "chronic-remission")]
    ChronicRemission,
    #[serde(rename = "toxicity")]
    Toxicity,
    #[serde(rename = "payment-pending")]
    PaymentPending,
    #[serde(rename = "patient-refusal")]
    PatientRefusal,
    #[serde(rename = "no-indication")]
    NoIndication,
    #[serde(rename = "regular-completion-with-substance-change")]
    RegularCompletionWithSubstanceChange,
    #[serde(rename = "payment-ended")]
    PaymentEnded,
    #[serde(rename = "other-therapy-chosen")]
    OtherTherapyChosen,
    #[serde(rename = "medical-reasons")]
    MedicalReasons,
    #[serde(rename = "other")]
    Other,
}

impl Default for Code {
    fn default() -> Code {
        Self::PatientWish
    }
}

