/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MvhMetadataModelProjectConsent {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "provisions")]
    pub provisions: Vec<models::MvhMetadataModelProjectConsentProvisionsInner>,
}

impl MvhMetadataModelProjectConsent {
    pub fn new(version: String, provisions: Vec<models::MvhMetadataModelProjectConsentProvisionsInner>) -> MvhMetadataModelProjectConsent {
        MvhMetadataModelProjectConsent {
            version,
            date: None,
            provisions,
        }
    }
}

