/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MvhMetadataModelProjectConsentProvisionsInner {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "purpose")]
    pub purpose: models::ModelProjectConsentPurpose,
    #[serde(rename = "type")]
    pub r#type: models::ConsentProvisionType,
}

impl MvhMetadataModelProjectConsentProvisionsInner {
    pub fn new(date: String, purpose: models::ModelProjectConsentPurpose, r#type: models::ConsentProvisionType) -> MvhMetadataModelProjectConsentProvisionsInner {
        MvhMetadataModelProjectConsentProvisionsInner {
            date,
            purpose,
            r#type,
        }
    }
}

