/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MvhMetadata : This DTO corresponds to a \"Prüfbericht\" for the Model Project. The structure is slightly different from the schema defined for the BfArM API: the conversion/mapping onto the later takes place in the central data node. Also, this DTO contains additional fields not represented in the BfArM \"Prüfbericht\" itself, but which are required for compilation of appendices 1/2 of the quarterly report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MvhMetadata {
    #[serde(rename = "modelProjectConsent")]
    pub model_project_consent: models::MvhMetadataModelProjectConsent,
    #[serde(rename = "researchConsents", skip_serializing_if = "Option::is_none")]
    pub research_consents: Option<Vec<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "episodeOfCare", skip_serializing_if = "Option::is_none")]
    pub episode_of_care: Option<models::Reference>,
    #[serde(rename = "reasonResearchConsentMissing", skip_serializing_if = "Option::is_none")]
    pub reason_research_consent_missing: Option<models::BroadConsentReasonMissing>,
    #[serde(rename = "transferTAN")]
    pub transfer_tan: String,
    #[serde(rename = "type")]
    pub r#type: models::MvhSubmissionType,
}

impl MvhMetadata {
    /// This DTO corresponds to a \"Prüfbericht\" for the Model Project. The structure is slightly different from the schema defined for the BfArM API: the conversion/mapping onto the later takes place in the central data node. Also, this DTO contains additional fields not represented in the BfArM \"Prüfbericht\" itself, but which are required for compilation of appendices 1/2 of the quarterly report.
    pub fn new(model_project_consent: models::MvhMetadataModelProjectConsent, transfer_tan: String, r#type: models::MvhSubmissionType) -> MvhMetadata {
        MvhMetadata {
            model_project_consent,
            research_consents: None,
            episode_of_care: None,
            reason_research_consent_missing: None,
            transfer_tan,
            r#type,
        }
    }
}

