/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OncoProcedure {
    #[serde(rename = "statusReason", skip_serializing_if = "Option::is_none")]
    pub status_reason: Option<models::MtbTherapyStatusReasonCoding>,
    #[serde(rename = "intent", skip_serializing_if = "Option::is_none")]
    pub intent: Option<models::MtbTherapyIntentCoding>,
    #[serde(rename = "therapyLine", skip_serializing_if = "Option::is_none")]
    pub therapy_line: Option<i32>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<models::Reference>,
    #[serde(rename = "code")]
    pub code: models::OncoProcedureTypeCoding,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "recordedOn")]
    pub recorded_on: String,
    #[serde(rename = "status")]
    pub status: models::TherapyStatusCoding,
    #[serde(rename = "basedOn", skip_serializing_if = "Option::is_none")]
    pub based_on: Option<models::Reference>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<models::PeriodDate>,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
}

impl OncoProcedure {
    pub fn new(code: models::OncoProcedureTypeCoding, id: String, recorded_on: String, status: models::TherapyStatusCoding, patient: models::Reference) -> OncoProcedure {
        OncoProcedure {
            status_reason: None,
            intent: None,
            therapy_line: None,
            reason: None,
            code,
            id,
            recorded_on,
            status,
            based_on: None,
            notes: None,
            period: None,
            patient,
        }
    }
}

