/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatientAddress {
    #[serde(rename = "municipalityCode")]
    pub municipality_code: String,
}

impl PatientAddress {
    pub fn new(municipality_code: String) -> PatientAddress {
        PatientAddress {
            municipality_code,
        }
    }
}

