/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::year_month_format::{serialize_option_year_month_format, serialize_year_month_format};
use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Patient {
    #[serde(rename = "dateOfDeath", skip_serializing_if = "Option::is_none")]
    #[serde(serialize_with = "serialize_option_year_month_format")]
    pub date_of_death: Option<String>,
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<models::Age>,
    #[serde(rename = "healthInsurance")]
    pub health_insurance: models::PatientHealthInsurance,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<models::PatientAddress>,
    #[serde(rename = "vitalStatus", skip_serializing_if = "Option::is_none")]
    pub vital_status: Option<models::VitalStatusCoding>,
    #[serde(rename = "birthDate")]
    #[serde(serialize_with = "serialize_year_month_format")]
    pub birth_date: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "gender")]
    pub gender: models::GenderCoding,
    #[serde(rename = "managingSite", skip_serializing_if = "Option::is_none")]
    pub managing_site: Option<models::Coding>,
}

impl Patient {
    pub fn new(health_insurance: models::PatientHealthInsurance, birth_date: String, id: String, gender: models::GenderCoding) -> Patient {
        Patient {
            date_of_death: None,
            age: None,
            health_insurance,
            address: None,
            vital_status: None,
            birth_date,
            id,
            gender,
            managing_site: None,
        }
    }
}

