/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatientHealthInsurance {
    #[serde(rename = "type")]
    pub r#type: models::HealthInsuranceTypeCoding,
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<models::Reference>,
}

impl PatientHealthInsurance {
    pub fn new(r#type: models::HealthInsuranceTypeCoding) -> PatientHealthInsurance {
        PatientHealthInsurance {
            r#type,
            reference: None,
        }
    }
}

