/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceStatus {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
    #[serde(rename = "effectiveDate")]
    pub effective_date: String,
    #[serde(rename = "value")]
    pub value: models::EcogCoding,
}

impl PerformanceStatus {
    pub fn new(id: String, patient: models::Reference, effective_date: String, value: models::EcogCoding) -> PerformanceStatus {
        PerformanceStatus {
            id,
            patient,
            effective_date,
            value,
        }
    }
}

