/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProteinExpression {
    #[serde(rename = "cpsScore", skip_serializing_if = "Option::is_none")]
    pub cps_score: Option<i32>,
    #[serde(rename = "icScore", skip_serializing_if = "Option::is_none")]
    pub ic_score: Option<models::ProteinExpressionIcScoreCoding>,
    #[serde(rename = "value")]
    pub value: models::ProteinExpressionResultCoding,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
    #[serde(rename = "protein")]
    pub protein: models::Coding,
    #[serde(rename = "tcScore", skip_serializing_if = "Option::is_none")]
    pub tc_score: Option<models::ProteinExpressionTcScoreCoding>,
    #[serde(rename = "tpsScore", skip_serializing_if = "Option::is_none")]
    pub tps_score: Option<i32>,
    #[serde(rename = "id")]
    pub id: String,
}

impl ProteinExpression {
    pub fn new(value: models::ProteinExpressionResultCoding, patient: models::Reference, protein: models::Coding, id: String) -> ProteinExpression {
        ProteinExpression {
            cps_score: None,
            ic_score: None,
            value,
            patient,
            protein,
            tc_score: None,
            tps_score: None,
            id,
        }
    }
}

