/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RnaSeq {
    #[serde(rename = "librarySize", skip_serializing_if = "Option::is_none")]
    pub library_size: Option<i32>,
    #[serde(rename = "localization", skip_serializing_if = "Option::is_none")]
    pub localization: Option<Vec<models::BaseVariantLocalizationCoding>>,
    #[serde(rename = "transcriptsPerMillion")]
    pub transcripts_per_million: f64,
    #[serde(rename = "cohortRanking", skip_serializing_if = "Option::is_none")]
    pub cohort_ranking: Option<i32>,
    #[serde(rename = "rawCounts")]
    pub raw_counts: i32,
    #[serde(rename = "variant")]
    pub variant: models::Reference,
    #[serde(rename = "transcriptId", skip_serializing_if = "Option::is_none")]
    pub transcript_id: Option<models::TranscriptId>,
    #[serde(rename = "externalIds", skip_serializing_if = "Option::is_none")]
    pub external_ids: Option<Vec<models::VariantExternalId>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tissueCorrectedExpression", skip_serializing_if = "Option::is_none")]
    pub tissue_corrected_expression: Option<bool>,
    #[serde(rename = "gene", skip_serializing_if = "Option::is_none")]
    pub gene: Option<models::Coding>,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
}

impl RnaSeq {
    pub fn new(transcripts_per_million: f64, raw_counts: i32, variant: models::Reference, id: String, patient: models::Reference) -> RnaSeq {
        RnaSeq {
            library_size: None,
            localization: None,
            transcripts_per_million,
            cohort_ranking: None,
            raw_counts,
            variant,
            transcript_id: None,
            external_ids: None,
            id,
            tissue_corrected_expression: None,
            gene: None,
            patient,
        }
    }
}

