/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptId {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "system")]
    pub system: System,
}

impl TranscriptId {
    pub fn new(value: String, system: System) -> TranscriptId {
        TranscriptId {
            value,
            system,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum System {
    #[serde(rename = "https://www.ncbi.nlm.nih.gov/refseq")]
    HttpsColonSlashSlashWwwNcbiNlmNihGovSlashRefseq,
    #[serde(rename = "https://www.ensembl.org")]
    HttpsColonSlashSlashWwwEnsemblOrg,
}

impl Default for System {
    fn default() -> System {
        Self::HttpsColonSlashSlashWwwNcbiNlmNihGovSlashRefseq
    }
}

