/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorStaging {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "method")]
    pub method: models::TumorStagingMethodCoding,
    #[serde(rename = "tnmClassification", skip_serializing_if = "Option::is_none")]
    pub tnm_classification: Option<models::TumorStagingTnmClassification>,
    #[serde(rename = "otherClassifications", skip_serializing_if = "Option::is_none")]
    pub other_classifications: Option<Vec<models::Coding>>,
}

impl TumorStaging {
    pub fn new(date: String, method: models::TumorStagingMethodCoding) -> TumorStaging {
        TumorStaging {
            date,
            method,
            tnm_classification: None,
            other_classifications: None,
        }
    }
}

