/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorSpecimenTypeCoding {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl TumorSpecimenTypeCoding {
    pub fn new(code: Code) -> TumorSpecimenTypeCoding {
        TumorSpecimenTypeCoding {
            code,
            display: None,
            system: None,
            version: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "fresh-tissue")]
    FreshTissue,
    #[serde(rename = "cryo-frozen")]
    CryoFrozen,
    #[serde(rename = "liquid-biopsy")]
    LiquidBiopsy,
    #[serde(rename = "FFPE")]
    Ffpe,
}

impl Default for Code {
    fn default() -> Code {
        Self::Unknown
    }
}

