/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorStagingTnmClassification {
    #[serde(rename = "tumor")]
    pub tumor: models::Coding,
    #[serde(rename = "nodes")]
    pub nodes: models::Coding,
    #[serde(rename = "metastasis")]
    pub metastasis: models::Coding,
}

impl TumorStagingTnmClassification {
    pub fn new(tumor: models::Coding, nodes: models::Coding, metastasis: models::Coding) -> TumorStagingTnmClassification {
        TumorStagingTnmClassification {
            tumor,
            nodes,
            metastasis,
        }
    }
}

