/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorCellContent {
    #[serde(rename = "method")]
    pub method: models::TumorCellContentMethodCoding,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "specimen")]
    pub specimen: models::Reference,
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "patient")]
    pub patient: models::Reference,
}

impl TumorCellContent {
    pub fn new(method: models::TumorCellContentMethodCoding, id: String, specimen: models::Reference, value: f64, patient: models::Reference) -> TumorCellContent {
        TumorCellContent {
            method,
            id,
            specimen,
            value,
            patient,
        }
    }
}

