/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorSpecimenCollection {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "method")]
    pub method: models::TumorSpecimenCollectionMethodCoding,
    #[serde(rename = "localization")]
    pub localization: models::TumorSpecimenCollectionLocalizationCoding,
}

impl TumorSpecimenCollection {
    pub fn new(method: models::TumorSpecimenCollectionMethodCoding, localization: models::TumorSpecimenCollectionLocalizationCoding) -> TumorSpecimenCollection {
        TumorSpecimenCollection {
            date: None,
            method,
            localization,
        }
    }
}

