/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TumorGrading {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "codes")]
    pub codes: Vec<models::Coding>,
}

impl TumorGrading {
    pub fn new(date: String, codes: Vec<models::Coding>) -> TumorGrading {
        TumorGrading {
            date,
            codes,
        }
    }
}

