/*
 * DNPM MTB Patient Record API
 *
 * OpenAPI representation of the DNPM DIP MTB Patient Record schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariantExternalId {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "system")]
    pub system: System,
}

impl VariantExternalId {
    pub fn new(value: String, system: System) -> VariantExternalId {
        VariantExternalId {
            value,
            system,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum System {
    #[serde(rename = "https://www.ncbi.nlm.nih.gov/entrez")]
    HttpsColonSlashSlashWwwNcbiNlmNihGovSlashEntrez,
    #[serde(rename = "https://www.ensembl.org")]
    HttpsColonSlashSlashWwwEnsemblOrg,
    #[serde(rename = "https://www.ncbi.nlm.nih.gov/snp")]
    HttpsColonSlashSlashWwwNcbiNlmNihGovSlashSnp,
    #[serde(rename = "https://cancer.sanger.ac.uk/cosmic")]
    HttpsColonSlashSlashCancerSangerAcUkSlashCosmic,
}

impl Default for System {
    fn default() -> System {
        Self::HttpsColonSlashSlashWwwNcbiNlmNihGovSlashEntrez
    }
}

