name: 'Run Tests'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [ 'created' ]

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        language:
          - java

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Java
      - uses: actions/setup-java@v5
        if: matrix.language == 'java'
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        if: matrix.language == 'java'
        uses: gradle/actions/setup-gradle@v3
      - name: Run tests
        if: matrix.language == 'java'
        working-directory: java
        run: ./gradlew test

  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - tests
    steps:
      - uses: actions/checkout@v6

      # Java
      - uses: actions/setup-java@v5
        if: matrix.language == 'java'
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        if: matrix.language == 'java'
        uses: gradle/actions/setup-gradle@v3
      - name: Publish to Maven repo
        if: matrix.language == 'java'
        working-directory: java
        run: ./gradlew build publish -Pdnpm_dev_token=${{ secrets.DNPM_DEV_TOKEN }}
